Rails 7 compatibility
wantable/omniship pull request #24
Opened 2022-12-30 18:19 UTC by mabid

2023-01-02 16:03 UTC, nbucciarelli approved these changes

2023-01-02 16:22 UTC, ksolkowski approved these changes
Maybe bump version up to .11

2023-01-02 16:31 UTC, fiestacasey requested changes
Agree with Kevin. You need to increase the version.rb and bundle install in this gem to update the version in gemspec

2023-01-03 17:43 UTC, fiestacasey approved these changes

2023-01-03 17:43 UTC, merged